package driver

import (
	"github.com/jmigpin/editor/ui/event"
	"github.com/veandco/go-sdl2/sdl"
)

var symmap = map[int]event.KeySym{
	sdl.K_0: event.KSym0,
	sdl.K_1: event.KSym1,
	sdl.K_2: event.KSym2,
	sdl.K_3: event.KSym3,
	sdl.K_4: event.KSym4,
	sdl.K_5: event.KSym5,
	sdl.K_6: event.KSym6,
	sdl.K_7: event.KSym7,
	sdl.K_8: event.KSym8,
	sdl.K_9: event.KSym9,

	sdl.K_a: event.KSymA,
	sdl.K_b: event.KSymB,
	sdl.K_c: event.KSymC,
	sdl.K_d: event.KSymD,
	sdl.K_e: event.KSymE,
	sdl.K_f: event.KSymF,
	sdl.K_g: event.KSymG,
	sdl.K_h: event.KSymH,
	sdl.K_i: event.KSymI,
	sdl.K_j: event.KSymJ,
	sdl.K_k: event.KSymK,
	sdl.K_l: event.KSymL,
	sdl.K_m: event.KSymM,
	sdl.K_n: event.KSymN,
	sdl.K_o: event.KSymO,
	sdl.K_p: event.KSymP,
	sdl.K_q: event.KSymQ,
	sdl.K_r: event.KSymR,
	sdl.K_s: event.KSymS,
	sdl.K_t: event.KSymT,
	sdl.K_u: event.KSymU,
	sdl.K_v: event.KSymV,
	sdl.K_w: event.KSymW,
	sdl.K_x: event.KSymX,
	sdl.K_y: event.KSymY,
	sdl.K_z: event.KSymZ,

	sdl.K_SPACE:     event.KSymSpace,
	sdl.K_BACKSPACE: event.KSymBackspace,
	sdl.K_RETURN2:   event.KSymReturn,
	sdl.K_ESCAPE:    event.KSymEscape,
	sdl.K_HOME:      event.KSymHome,
	sdl.K_LEFT:      event.KSymLeft,
	sdl.K_UP:        event.KSymUp,
	sdl.K_RIGHT:     event.KSymRight,
	sdl.K_DOWN:      event.KSymDown,
	sdl.K_PAGEUP:    event.KSymPageUp,
	sdl.K_PAGEDOWN:  event.KSymPageDown,
	sdl.K_END:       event.KSymEnd,
	sdl.K_INSERT:    event.KSymInsert,
	sdl.K_LSHIFT:    event.KSymShiftL,
	sdl.K_RSHIFT:    event.KSymShiftR,
	sdl.K_LCTRL:     event.KSymControlL,
	sdl.K_RCTRL:     event.KSymControlR,
	sdl.K_LALT:      event.KSymAltL,
	sdl.K_RALT:      event.KSymAltR,
	sdl.K_MODE:      event.KSymAltGr,
	sdl.K_LGUI:      event.KSymSuperL, // windows key
	sdl.K_RGUI:      event.KSymSuperR,
	sdl.K_DELETE:    event.KSymDelete,
	sdl.K_TAB:       event.KSymTab,

	sdl.K_NUMLOCKCLEAR: event.KSymNumLock,
	sdl.K_CAPSLOCK:     event.KSymCapsLock, // only capitalizes letters,

	sdl.K_EXCLAIM:      event.KSymExclam,      // !,
	sdl.K_QUOTEDBL:     event.KSymDoubleQuote, // ",
	sdl.K_HASH:         event.KSymNumberSign,  // #,
	sdl.K_DOLLAR:       event.KSymDollar,      // $,
	sdl.K_PERCENT:      event.KSymPercent,     // %,
	sdl.K_AMPERSAND:    event.KSymAmpersand,   // &,
	sdl.K_QUOTE:        event.KSymApostrophe,  // ',
	sdl.K_LEFTPAREN:    event.KSymParentL,     // (,
	sdl.K_RIGHTPAREN:   event.KSymParentR,     // ),
	sdl.K_ASTERISK:     event.KSymAsterisk,    // *,
	sdl.K_PLUS:         event.KSymPlus,        // +,
	sdl.K_COMMA:        event.KSymComma,       // ,,
	sdl.K_MINUS:        event.KSymMinus,       // -,
	sdl.K_PERIOD:       event.KSymPeriod,      // .,
	sdl.K_SLASH:        event.KSymSlash,       // /,
	sdl.K_BACKSLASH:    event.KSymBackSlash,   // \,
	sdl.K_COLON:        event.KSymColon,       // :,
	sdl.K_SEMICOLON:    event.KSymSemicolon,   // ;,
	sdl.K_LESS:         event.KSymLess,        // <,
	sdl.K_EQUALS:       event.KSymEqual,       // =,
	sdl.K_GREATER:      event.KSymGreater,     // >,
	sdl.K_QUESTION:     event.KSymQuestion,    // ?,
	sdl.K_AT:           event.KSymAt,          // @,
	sdl.K_LEFTBRACKET:  event.KSymBracketL,    // [,
	sdl.K_RIGHTBRACKET: event.KSymBracketR,    // ],

	sdl.K_BACKQUOTE: event.KSymGrave, // `,
	// sdl.K_ACUTE:     event.KSymAcute,      // ´,
	sdl.K_CARET: event.KSymCircumflex, // ^,
	// sdl.K_TILDE: event.KSymTilde,      // ~,
	// sdl.K_CED:      event.KSymCedilla,    // ¸,
	// sdl.K_BREVE:      event.KSymBreve,      // ˘,
	// sdl.K_CARON:      event.KSymCaron,      // ˇ,
	// sdl.K_DIARE:      event.KSymDiaresis,   // ¨,
	// sdl.K_RING:      event.KSymRingAbove,  // ˚,
	// sdl.K_MACR:      event.KSymMacron,     // ¯,

	sdl.K_F1:  event.KSymF1,
	sdl.K_F2:  event.KSymF2,
	sdl.K_F3:  event.KSymF3,
	sdl.K_F4:  event.KSymF4,
	sdl.K_F5:  event.KSymF5,
	sdl.K_F6:  event.KSymF6,
	sdl.K_F7:  event.KSymF7,
	sdl.K_F8:  event.KSymF8,
	sdl.K_F9:  event.KSymF9,
	sdl.K_F10: event.KSymF10,
	sdl.K_F11: event.KSymF11,
	sdl.K_F12: event.KSymF12,
	sdl.K_F13: event.KSymF13,
	sdl.K_F14: event.KSymF14,
	sdl.K_F15: event.KSymF15,
	sdl.K_F16: event.KSymF16,

	sdl.K_KP_0:        event.KSymKeypad0,
	sdl.K_KP_1:        event.KSymKeypad1,
	sdl.K_KP_2:        event.KSymKeypad2,
	sdl.K_KP_3:        event.KSymKeypad3,
	sdl.K_KP_4:        event.KSymKeypad4,
	sdl.K_KP_5:        event.KSymKeypad5,
	sdl.K_KP_6:        event.KSymKeypad6,
	sdl.K_KP_7:        event.KSymKeypad7,
	sdl.K_KP_8:        event.KSymKeypad8,
	sdl.K_KP_9:        event.KSymKeypad9,
	sdl.K_KP_MULTIPLY: event.KSymKeypadMultiply,
	sdl.K_KP_PLUS:     event.KSymKeypadAdd,
	sdl.K_KP_MINUS:    event.KSymKeypadSubtract,
	sdl.K_KP_DECIMAL:  event.KSymKeypadDecimal,
	sdl.K_KP_DIVIDE:   event.KSymKeypadDivide,

	sdl.K_VOLUMEUP:   event.KSymVolumeUp,
	sdl.K_VOLUMEDOWN: event.KSymVolumeDown,
	sdl.K_MUTE:       event.KSymMute,

	// sdl.K_MULTI: event.KSymMultiKey,
	sdl.K_MENU: event.KSymMenu,
}
